name       : libflac
version    : 1.4.2
release    : 15
source     :
    - https://github.com/xiph/flac/releases/download/1.4.2/flac-1.4.2.tar.xz : e322d58a1f48d23d9dd38f432672865f6f79e73a6f9cc5a5f57fcaa83eb5a8e4
license    :
    - BSD-3-Clause
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Encoder/decoder for the Free Lossless Audio Codec
description: |
    FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality.
builddeps  :
    - pkgconfig32(ogg)
    - glibc-32bit-devel
    - nasm
avx2       : yes
emul32     : yes
setup      : |
    export CFLAGS="${CFLAGS/-g2/}"
    %autogen --disable-static --disable-xmms-plugin
build      : |
    %make
install    : |
    %make_install

    # Save space as only want libFLAC.so*
    if [[ ! -z "${AVX2BUILD}" ]]; then
        rm -rf $installdir/%libdir%/libFLAC++.*
    fi
