name       : libflac
version    : 1.3.1
release    : 7
source     :
    - https://sourceforge.net/projects/flac/files/flac-src/flac-1.3.1.tar.xz : 4773c0099dba767d963fd92143263be338c48702172e8754b9bc5103efe1c56c
license    :
    - LGPL-2.0
summary    : Encoder/decoder for the Free Lossless Audio Codec
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
    - nasm
    - glibc-32bit-devel
    - libstdc++-32bit
    - libgcc-32bit
emul32     : yes
description: |
    FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality.
setup      : |
    export CFLAGS="${CFLAGS/-g2/}"
    export CFLAGS="${CFLAGS/-flto/} -funroll-loops -O3 -falign-functions=32"
    %autogen --disable-static --disable-xmms-plugin --prefix=/usr
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        CC="gcc -m32" %make V=1
    else
        CC=gcc %make V=1
    fi
install    : |
    %make_install
