name       : libflac
version    : 1.3.2
release    : 11
source     :
    - https://github.com/xiph/flac/archive/1.3.2.tar.gz : 4bfa8b41642d3b7375ad283a8b1292de1dac7a669b1fd959d18c2ac4a6d2a108
license    :
    - BSD-3-Clause
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Encoder/decoder for the Free Lossless Audio Codec
description: |
    FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality.
builddeps  :
    - pkgconfig32(ogg)
    - glibc-32bit-devel
    - nasm
avx2       : yes
emul32     : yes
setup      : |
    %apply_patches

    export CFLAGS="${CFLAGS/-g2/}"
    export CFLAGS="${CFLAGS/-flto/}"
    %autogen --disable-static --disable-xmms-plugin
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        CC="gcc -m32" %make V=1
    else
        CC=gcc %make V=1
    fi
install    : |
    %make_install

    # Save space as only want libFLAC.so*
    if [[ ! -z "${AVX2BUILD}" ]]; then
        rm -rf $installdir/%libdir%/libFLAC++.*
    fi
