name       : libflac
version    : 1.3.4
release    : 14
source     :
    - https://github.com/xiph/flac/releases/download/1.3.4/flac-1.3.4.tar.xz : 8ff0607e75a322dd7cd6ec48f4f225471404ae2730d0ea945127b1355155e737
license    :
    - BSD-3-Clause
    - GFDL-1.1-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Encoder/decoder for the Free Lossless Audio Codec
description: |
    FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality.
builddeps  :
    - pkgconfig32(ogg)
    - glibc-32bit-devel
    - nasm
avx2       : yes
emul32     : yes
setup      : |
    export CFLAGS="${CFLAGS/-g2/}"
    %autogen --disable-static --disable-xmms-plugin
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        CC="gcc -m32" %make V=1
    else
        CC=gcc %make V=1
    fi
install    : |
    %make_install

    # Save space as only want libFLAC.so*
    if [[ ! -z "${AVX2BUILD}" ]]; then
        rm -rf $installdir/%libdir%/libFLAC++.*
    fi
