name       : libflac
version    : 1.3.2
release    : 8
source     :
    - http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz : 91cfc3ed61dc40f47f050a109b08610667d73477af6ef36dcad31c31a4a8d53f
license    :
    - LGPL-2.0
summary    : Encoder/decoder for the Free Lossless Audio Codec
component  : multimedia.codecs
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
    - nasm
    - glibc-32bit-devel
    - libstdc++-32bit
    - libgcc-32bit
emul32     : yes
description: |
    FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but lossless, meaning that audio is compressed in FLAC without any loss in quality.
setup      : |
    export CFLAGS="${CFLAGS/-g2/}"
    export CFLAGS="${CFLAGS/-flto/} -funroll-loops -O3 -falign-functions=32"
    %autogen --disable-static --disable-xmms-plugin --prefix=/usr
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        CC="gcc -m32" %make V=1
    else
        CC=gcc %make V=1
    fi
install    : |
    %make_install
